name: AGENT19

on:
  workflow_dispatch:  # Pořád můžeš spustit ručně tlačítkem
  push:               # Spustí se při každém nahrání kódu
    branches: [ "main" ]
  schedule:
    - cron: '0 15 * * *' 

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run agent
        run: node agent.js
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          MAIL_USER: ${{ secrets.MAIL_USER }}